using UnityEngine;
using System.Collections;

// Template class for most of the behaviors covered
public class AgentBehaviour : MonoBehaviour
{
    public GameObject target;
    protected Agent agent;
   
    public virtual void Awake()
    {
        agent = GetComponent<Agent>();
    }
    
    public virtual void Update()
    {
        agent.SetSteering(GetSteering());
    }
    
    public virtual Steering GetSteering()
    {
        return new Steering();
    }

      
    // Finds direction of rotation after two 
    // orientation values are subtracted
    // - Added with Facing Script
    public float MapToRange(float rotation)
    {
        rotation %= 360.0f;
        if (Mathf.Abs(rotation) > 180.0f)
        {
            if (rotation < 0.0f)
                rotation += 360.0f;
            else
                rotation -= 360.0f;
        }
        return rotation;
    }

    // Convert an orientation value to a vector 
    // - Added with Wanderer Script
    public Vector3 OriToVec(float orientation)
    {
        Vector3 vector = Vector3.zero;
        vector.x = Mathf.Sin(orientation * Mathf.Deg2Rad) * 1.0f;
        vector.z = Mathf.Cos(orientation * Mathf.Deg2Rad) * 1.0f;
        return vector.normalized;
    }
}
 